-- Database for ORM CURD
CREATE DATABASE BookStoreORM;

USE BookStoreORM;

CREATE TABLE BK01(
	K01F01 INT AUTO_INCREMENT PRIMARY KEY COMMENT "ID",
    K01F02 VARCHAR(150) NOT NULL COMMENT "Title",
    K01F03 VARCHAR(100) NOT NULL COMMENT "Author",
    K01F04 VARCHAR(100) COMMENT "Category",
    K01F05 DECIMAL(8,2) NOT NULL COMMENT "Price",
    K01F06 DATETIME NOT NULL COMMENT "Created At",
    K01F07 DATETIME NOT NULL COMMENT "Updated At"
) COMMENT "Books";